export const employeeSchemas = {
  Employee: {
    type: "object",
    properties: {
      _id: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b801" },
      orgId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7c8" },
      employeeCode: { type: "string", example: "EMP-00001" },
      firstName: { type: "string", example: "Jane" },
      lastName: { type: "string", example: "Doe" },
      email: { type: "string", format: "email", example: "jane.doe@acme.com" },
      jobTitle: { type: "string", example: "Lead Software Engineer" },
      departmentId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7f1" },
      role: {
        type: "string",
        enum: ["HR", "Employee"],
        example: "Employee",
      },
      level: {
        type: "string",
        enum: ["junior", "mid", "senior", "lead", "manager"],
        example: "lead",
      },
      countryId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7d1" },
      currencyId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7e1" },
      salary: { type: "number", minimum: 1, example: 120000 },
      hireDate: { type: "string", format: "date", example: "2023-01-15" },
      employmentType: {
        type: "string",
        enum: ["Full-time", "Part-time", "Contract"],
        example: "Full-time",
      },
      leaveDate: { type: "string", format: "date", nullable: true },
      status: { type: "string", enum: ["Active", "Inactive"], example: "Active" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateEmployeeInput: {
    type: "object",
    required: [
      "employeeCode",
      "firstName",
      "lastName",
      "email",
      "jobTitle",
      "departmentId",
      "level",
      "countryId",
      "currencyId",
      "salary",
      "hireDate",
      "employmentType",
    ],
    properties: {
      employeeCode: { type: "string", example: "EMP-00001" },
      firstName: { type: "string", example: "Jane" },
      lastName: { type: "string", example: "Doe" },
      email: { type: "string", format: "email", example: "jane.doe@acme.com" },
      jobTitle: { type: "string", example: "Lead Software Engineer" },
      departmentId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7f1" },
      role: {
        type: "string",
        enum: ["HR", "Employee"],
        default: "Employee",
        example: "Employee",
      },
      level: {
        type: "string",
        enum: ["junior", "mid", "senior", "lead", "manager"],
        example: "lead",
      },
      countryId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7d1" },
      currencyId: { type: "string", example: "64e0a1f8b1c2d3e4f5a6b7e1" },
      salary: { type: "number", minimum: 1, example: 120000 },
      hireDate: { type: "string", format: "date", example: "2023-01-15" },
      employmentType: {
        type: "string",
        enum: ["Full-time", "Part-time", "Contract"],
        example: "Full-time",
      },
      leaveDate: { type: "string", format: "date" },
      status: { type: "string", enum: ["Active", "Inactive"], default: "Active" },
    },
  },
};
